name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          year: [2024]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate badge info
      run: |
        output=$(make test YEAR=2024 2>&1 | tee /dev/stdout)

        tests=$(echo "$output" | grep -oP '(?<=Ran )[0-9]+(?= tests in)')
        passes=$(echo "$output" | head -n 1 | grep -o '\.' | wc -l)

        if [[ $passes -eq $tests ]]; then
            colour=success
        elif [[ $passes -gt 0 ]]; then
            colour=important
        else
            colour=critical
        fi

        sed -i "s/[0-9]\+\/[0-9]\+-[a-z]\+/${passes}\/${tests}-${colour}/" ${{ matrix.year }}/README.md

    - name: Check for changes
      id: git_status
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: steps.git_status.outputs.changes == 'true'
      with:
        commit_message: Update ${{ matrix.year }} test badge
        file_pattern: ${{ matrix.year }}/README.md