name: Daily Setup Commands for Advent of Code

on:
  schedule:
    # Run daily at 6am UTC for the first 25 days of December
    - cron: "0 6 1-25 12 *"
  workflow_dispatch:

jobs:
  setup-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch example file
      env:
        AOC_SESSION: ${{ secrets.AOC_SESSION }}
      run: make fetch-example

    - name: Generate solution and test files
      run: make generate

    - name: Check for changes
      id: git_status
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: steps.git_status.outputs.changes == 'true'
      with:
        commit_message: Generated files for the new day
